theme: minima
title: Krabbelk채fer Stutensee
author: null
description: >
  Verantwortlich f체r Inhalte: Melanie Reuter, info@krabbelk채fer-stutensee.de in Stutensee B체chig
header_pages:
  - _pages/about.md
  - _pages/aktuelles.md  

include:
    - _pages
